-- Generado automáticamente desde src/data/clientes.js (export-data.mjs + generate-insert-sql.mjs)
-- Revisar unas cuantas filas contra el panel antes de darle a Run, por tratarse de datos reales de facturación.
insert into public.clientes (
  nombre, drive, email, estado, fecha_inicio, fecha_fin,
  fecha_primer_pago, fecha_segundo_pago, fecha_tercer_pago,
  forma_pago, pago, primer_pago, segundo_pago, tercer_pago,
  renueva, forma_renovacion, importe_renovacion, fecha_renovacion,
  servicio_contratado, telefono, tipo_cliente
) values
('Juan Daniel Febles Choc', null, null, 'ACTIVO', '2026-03-09', '2026-06-07', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Eva Galobardes', null, null, 'ACTIVO', '2026-03-16', '2026-07-05', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Facundo Recalde', null, null, 'NO ACTIVO', '2026-03-09', '2026-04-12', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Carlos Sotos', null, null, 'NO ACTIVO', '2026-03-09', '2026-04-12', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('David Gandia', null, null, 'NO ACTIVO', '2026-03-09', '2026-04-12', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Marcos Cano García', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'LOW TICKET'),
('Roberto Navarro Navares', null, null, 'NO ACTIVO', '2026-04-01', '2026-05-03', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Jose Manuel Arroyo Pineda', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Jesus Gómez', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Jorge Garnica', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'LOW TICKET'),
('Eva María Cascante Martínez', null, null, 'ACTIVO', '2026-02-01', '2026-05-31', null, null, null, 'Bizum', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Jessica Pizarro', null, null, 'NO ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Transferencia', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Jose Vicente Muñoz', null, null, 'NO ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Banta Tunkara', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'LOW TICKET'),
('Antonio Baca', null, null, 'NO ACTIVO', '2026-03-01', '2026-03-31', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Maria jesus García Ortíz', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Yeray Santiago Cabrera Ruíz', null, null, 'ACTIVO', '2026-03-01', '2026-05-31', null, null, null, 'Stripe', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Alberto Sanz Saiz', null, null, 'ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Adrián López Ávila', null, null, 'NO ACTIVO', '2026-03-01', '2026-03-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Paco Díaz Sáez', null, null, 'NO ACTIVO', '2026-04-01', '2026-05-03', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Guille Miralles', null, null, 'ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Bizum', '3 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('iker Gómez Adarve', null, null, 'ACTIVO', '2026-05-01', '2026-08-02', null, null, null, 'Transferencia', 'COMPLETO', 199, null, null, 'No', null, null, null, 'Trimestral', null, 'LOW TICKET'),
('Daniel Ortega', null, null, 'ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Stripe', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Lucas Alsina', null, null, 'ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Stripe', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Paola Rosas', null, null, 'NO ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Transferencia', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Greissy García', null, null, 'ACTIVO', '2026-02-01', '2026-05-03', null, null, null, 'Stripe', '3 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Jose Antonio LLoret Cortés', null, null, 'ACTIVO', '2026-01-01', '2026-07-05', null, null, null, 'Bizum', '3 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Juan Diego Gómez Mateo', null, null, 'NO ACTIVO', '2026-01-01', '2026-04-05', null, null, null, 'Stripe', '2 PLAZOS', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Rubén Rupérez', null, null, 'ACTIVO', '2026-02-01', '2026-05-30', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Miguel Miranda', null, null, 'ACTIVO', '2026-03-01', '2026-04-19', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'HIGH TICKET'),
('José Herráiz', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Transferencia', 'COMPLETO', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('Adán González', null, null, 'ACTIVO', '2026-01-01', '2026-07-05', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Semestral', null, 'HIGH TICKET'),
('Elena Landaburu', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Transferencia', 'COMPLETO', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('Jose Miguel Cabezas Gamonal', null, null, 'NO ACTIVO', '2026-04-01', '2026-04-30', null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'Yes', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Victor Bustara', null, null, 'NO ACTIVO', null, '2026-04-05', null, null, null, 'Transferencia', 'COMPLETO', null, null, null, 'No', null, null, null, 'Trimestral', null, 'HIGH TICKET'),
('Leire Cadierno Martín', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Transferencia', 'COMPLETO', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('Ángel Díaz Díaz', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Bizum', '3 PLAZOS', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('Adrián Cortés', null, null, 'ACTIVO', null, null, null, null, null, 'Bizum', 'COMPLETO', null, null, null, 'No', null, null, null, 'Mensual', null, 'LOW TICKET'),
('Pascual Miguel Cicoira ', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Stripe', '3 PLAZOS', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('María Hernández', null, null, 'ACTIVO', '2026-01-01', '2026-12-31', null, null, null, 'Stripe', 'COMPLETO', null, null, null, 'No', null, null, null, 'Anual', null, 'HIGH TICKET'),
('Sidi Mohamed Ajjaji', null, 'sidizek@gmail.com', 'ACTIVO', '2026-04-01', '2026-07-04', '2026-04-06', null, null, 'Transferencia', 'COMPLETO', 597, null, null, 'No', null, null, null, 'Trimestral', '664121704', 'HIGH TICKET'),
('Víctor Fernández Gómez', null, 'victorferngom@gmail.com', 'ACTIVO', '2026-04-01', '2026-07-04', '2026-04-06', null, null, 'Stripe', 'COMPLETO', 597, null, null, 'No', null, null, null, 'Trimestral', '679047884', 'HIGH TICKET'),
('Sandra Galano Roqueta', 'https://drive.google.com/drive/folders/17GneyxQxK_yp8tao1A5NAyGA82xogP3D?usp=share_link', 'sandragalano@hotmail.com', 'ACTIVO', '2026-04-01', '2026-07-04', '2026-03-31', null, null, 'Bizum', '2 PLAZOS', 300, 300, null, 'No', null, null, null, 'Trimestral', '616559618', 'HIGH TICKET'),
('Maite Secaduras', 'https://drive.google.com/drive/folders/11_ZUyeJfgHGkUCYWQmX_WbK-184POzHM?usp=share_link', 'mso25@hotmail.com', 'ACTIVO', '2026-04-01', '2026-07-04', '2026-04-01', null, null, 'Bizum', '2 PLAZOS', 247, null, null, 'No', null, null, null, 'Trimestral', '635553336', 'HIGH TICKET'),
('David Chaparro Rodríguez', 'https://drive.google.com/drive/folders/1svVZ0AN2yTKbaKYuwkwLMm46Ar43HjCw?usp=share_link', 'davidmatinee@gmail.com', 'ACTIVO', '2026-04-01', '2026-07-04', '2026-03-31', null, null, 'Bizum', '3 PLAZOS', 250, 125, 125, 'No', null, null, null, 'Trimestral', '607472477', 'HIGH TICKET'),
('Raúl Nieto García', 'https://drive.google.com/drive/folders/1HPyCFXuqu5yp-gtXwuL-P15MYItFpdDs?usp=share_link', 'nietograul@gmail.com', 'ACTIVO', '2026-05-01', '2026-07-31', '2026-04-14', null, null, 'Transferencia', 'COMPLETO', 547, null, null, 'No', null, null, null, 'Trimestral', '652465969', 'HIGH TICKET'),
('Jaime Gabriel Privado López', 'https://drive.google.com/drive/folders/1B2OGa3zlIF5G_g70YOZXyNZ9s0k1RXQH?usp=share_link', 'jaimeprivadolopez21@gmail.com', 'ACTIVO', '2026-05-01', '2026-09-05', '2026-04-16', null, null, 'Stripe', 'COMPLETO', 597, null, null, 'No', null, null, null, 'Cuatrimestral', '711747439', 'HIGH TICKET'),
('ALEJANDRO VALENCIA', 'https://drive.google.com/drive/folders/1vOXa8AK_RL8bWhGprAxSH6IA4UQvAmRh?usp=share_link', 'jandro.valencia2@gmail.com', 'ACTIVO', '2026-05-01', '2026-07-31', '2026-04-18', null, null, 'Stripe', 'COMPLETO', 180, null, null, 'No', null, null, null, 'Trimestral', '652772430', 'LOW TICKET'),
('Valentín Bernales', 'https://drive.google.com/drive/folders/1n-JWmU45ASarZWUlmJ8cfouzAQbROzct?usp=share_link', 'drbernalesodino@gmail.com', 'ACTIVO', '2026-05-01', '2026-09-05', null, null, null, 'Stripe', '2 PLAZOS', 60, 537, null, 'No', null, null, null, 'Cuatrimestral', '692244801', 'HIGH TICKET'),
('Chiara Tonoli', 'https://drive.google.com/drive/folders/1tlLx_CO8Y1Mf0oQ6vSrznfhOZZwT26-t?usp=share_link', 'chiton2106@gmail.com', 'ACTIVO', '2026-05-01', '2026-09-05', null, null, null, 'Stripe', 'COMPLETO', 180, null, null, 'No', null, null, null, 'Trimestral', '+393445789690', 'LOW TICKET'),
('Celeste Mercado', 'https://drive.google.com/drive/folders/1TeIe_v7_bdfhTsjy-ZOWoqsUrW0PrkUB?usp=share_link', 'celestesab@gmail.com', 'ACTIVO', '2026-05-01', '2026-05-31', '2026-04-28', null, null, 'Stripe', 'COMPLETO', 79, null, null, 'No', null, null, null, 'Mensual', '666233067', 'LOW TICKET'),
('Pau Espejo Romero', 'https://drive.google.com/drive/folders/1fIFBYTTiCOr1dSrUjjlZXBx-PssvTLTu?usp=share_link', 'pespejoromero@gmail.com', 'ACTIVO', '2026-05-15', '2026-09-30', '2026-05-07', null, null, 'Stripe', 'COMPLETO', 697, null, null, 'No', null, null, null, 'Cuatrimestral', '684179700', 'HIGH TICKET'),
('Alejandro Luque', 'https://drive.google.com/drive/folders/1i9XNbLI3gsyfWQldcGBjQqvwvZsR71r1?usp=share_link', 'alexluque270@gmail.com', 'ACTIVO', '2026-06-01', '2026-10-03', null, null, null, 'Stripe', 'COMPLETO', 597, null, null, 'No', null, null, null, 'Cuatrimestral', '682645798', 'HIGH TICKET'),
('Álvaro González', 'https://drive.google.com/drive/folders/1Nkzwn3lXNuNRjaotooyt1mlaUzkBmcxc?usp=share_link', 'alvarogdoello@gmail.com', 'ACTIVO', '2026-06-01', '2026-08-29', null, null, null, 'Stripe', 'COMPLETO', 497, null, null, 'No', null, null, null, 'Trimestral', '669941092', 'HIGH TICKET'),
('Carmen Ortega', 'https://drive.google.com/drive/folders/1FtSWVW4omLVpuXvu-e-RkloOzcK43B29?usp=share_link', 'carmenwejar13@gmail.com', 'ACTIVO', '2026-06-01', '2026-10-03', '2026-05-27', '2026-06-27', null, 'Stripe', '2 PLAZOS', 350, 350, null, 'No', null, null, null, 'Cuatrimestral', '618395204', 'HIGH TICKET');
