-- 45 ideas de contenido traspasadas desde Recordatorios (lista "Ideas Post").
-- Cada una entra sin fecha (van al backlog / Listado de ideas) y en estado
-- "Idea", sin editor asignado todavía — se completan desde el panel.
insert into public.contenido_ideas (id, titulo, descripcion, estado) values
('idea-post-01', 'Guía: cómo entrenar lesionado (y qué pasa si no entrenas)', 'Guía para entrenar lesionado (YouTube)…. Consecuencias de no entrenar', 'Idea'),
('idea-post-02', 'Ejercicio de hombro estilo Cbum', 'Ejercicio hombro cbum', 'Idea'),
('idea-post-03', 'Los tratamientos curan pero no preparan', 'El concepto es que no se trata de los tratamiento porque una cosa muy importante después de una lección es ver qué deporte la persona en caso de que practique si no pasa nada pero claro esos tratamientos te curan pero no te reparan eso es el concepto mejor dicho no te preparan', 'Idea'),
('idea-post-04', 'Analogía de las 34 piezas: cómo funciona el ejercicio', 'Te voy a explicar cómo funciona el ejercicio y pongo el ejemplo de coger 34 piezas que por separado no sirven para nada, pero si lo juntas y dependiendo cómo lo juntes si más o menos', 'Idea'),
('idea-post-05', 'El problema de los ejercicios "quita-dolor"', 'El problema de los ejercicios que dicen que te quitan el dolor es que puede que te lo quiten, pero hay que mirar el después que es si tolera a cargado', 'Idea'),
('idea-post-06', 'No existe el ejercicio mágico', 'No es el ejercicio mágico es todo lo demás', 'Idea'),
('idea-post-07', 'No es falta de disciplina, es tu hombro', 'Corrígeme si me equivoco, pero muchos te prometen tener el cuerpo … y lo tuyo no es falta de disciplina es que estás jodido del hombro y si podemos solucionar eso???', 'Idea'),
('idea-post-08', 'Peso muerto disfrazado de Iron Man (miedo)', 'Video de peso muerto y yo disfrazado de iron máster (miedo y diablo)', 'Idea'),
('idea-post-09', '¿Volver a entrenar es posible? (cuidado con el GPT)', 'Volver a entrenar es posible? No te enseño mi gpt porque está educado u me conoce, pero investiga a gente con tu lesión y no te quedes con lo malo', 'Idea'),
('idea-post-10', '"Fortalecer" con gomas: de dónde viene de verdad', 'Eso de fortalece y te ponen con gomitas a ver el fortalecer viene del entrenamiento y entrenamiento de hecho de las base sobrecarga positiva y entonces hay que tratarte como un Entrenamiento', 'Idea'),
('idea-post-11', 'Ayudar con dureza también es ayudar', 'Si puedes ayuda y no eres amable, fue querer la ayuda te doy un consejo mal, no está entrena fuerte porque no estás mal y no eres capaz de invertir es que no estás mal', 'Idea'),
('idea-post-12', 'Si no entrenas por la lesión, no hay resultados', 'Si tu lesión de hombro no te deja entrenar, no estás entrenando, vas por que te dices que tienes que ir, pero tienes resultados', 'Idea'),
('idea-post-13', '"Solo con gomas" — cuidado con los consejos fáciles', 'Suerte si es solo gomitas, y ahora viene el listo que me dicd que se recupero', 'Idea'),
('idea-post-14', 'Por qué las terapias pasivas no son la solución', 'No encuentras la solución porque los ejercicios y las terapias pasivas no es lo importante', 'Idea'),
('idea-post-15', 'Bursitis: el problema viene al volver a entrenar', 'Bursitis reposa, no hace falta nada más, pero el problema viene cuando entrenas después', 'Idea'),
('idea-post-16', 'Por qué un ejercicio no funciona igual para todos', 'Porque hay ejercicios que no funcionan (depende de la persona)', 'Idea'),
('idea-post-17', 'Lo jodido de una lesión de hombro: probarlo todo y seguir igual', 'Sabes que los jodido de una lesión de hombro que no puedes entrenar espalda pecho que no puedes entrenar, pecho espalda y lo jodido también que has probado de todo y sigues igual y no es porque no te haya funcionado sino porque falta algo más', 'Idea'),
('idea-post-18', 'No fue el ejercicio, fue la mala gestión de cargas', 'La mayoría de las veces no es por el ejercicio que te lesiono, fue por mala gestión de las cargas', 'Idea'),
('idea-post-19', 'Cuanto antes empieces, mejor (cambios neuroplásticos)', 'Si llevas poco tiempo con dolor es el mejor momento de empezar, porque cuanto más tarda más cambios neuro plásticos, etc. etc. se producen en tu organismo y peor y más difícil quitar el dolor mejor ahora', 'Idea'),
('idea-post-20', 'Ahora que lo sabes, la decisión es tuya', 'Y ahora que sabes esto es decisión tuya yo te lo advertí si no le puedes solución va peor que sepas que no es culpa de nadie ni de nada sino solo tuya', 'Idea'),
('idea-post-21', 'El entrenamiento de fuerza no da miedo', 'Entrenamiento de fuerza es cualquier cosa, así que no tengas miedo, puede ser el hecho de moverte solo eso entrenamiento de fuerza. No tengas miedo que te lo pauten.', 'Idea'),
('idea-post-22', 'El secreto es la constancia (que pierdes con la lesión)', 'El secreto de un buen físico es la constancia, constancia que no tienes por la lesión', 'Idea'),
('idea-post-23', 'El iceberg de tu lesión', 'Iceberg: punta tu lesión y resto todo lo demás', 'Idea'),
('idea-post-24', 'Por qué las terapias no preparan el tejido', 'Las terapias no funcionan, no porque sean malas, sino porque no preparan el tejido al contexto y al deporte de la persona', 'Idea'),
('idea-post-25', 'El miedo nunca ha mejorado a nadie', 'El miedo nunca ha mejorado a nadie, sin importar a qué teman (hacer incapie en la importancia de mejorar el miedo)', 'Idea'),
('idea-post-26', 'Press banca: evitar el dolor te quita los "gains"', 'Press de banca: recorrido por dolor, te estás quitando donde más Gains tiene el ejercicio', 'Idea'),
('idea-post-27', 'Si entrenas a medio gas, mejor no entrenes', 'Sinceramente si tienes que entrenar a medio gas, no entrenes', 'Idea'),
('idea-post-28', 'Rotaciones: mancuernas o gomas, ¿cuál elegir?', 'Dos opciones : rotaciones mancuernas o gomas, ….', 'Idea'),
('idea-post-29', 'Excéntrico y progresión: cuándo meterlos', 'Ojalá fuese fácil, (excéntrico), progresiva?, pero cuando meterlo?', 'Idea'),
('idea-post-30', 'Si sigues con dolor mucho tiempo, es decisión tuya', 'Si llevas tiempo con dolor solo es porque tú quieres', 'Idea'),
('idea-post-31', 'La educación del dolor importa más que el ejercicio', 'Más importante que los ejercicios es la educación del dolor', 'Idea'),
('idea-post-32', 'Te curas cuando dejas que te ayuden', 'El que se cura es solo porque deja que otros lo ayuden', 'Idea'),
('idea-post-33', 'Ejemplos de ejercicios sin control de cargas', 'Ejercicios sin control de cargas (ejemplos)', 'Idea'),
('idea-post-34', 'Blanco o negro: cuando no saben ver la escala de grises', 'Cuando te dicen blanco o negro es porque no saben proponer escala de grises', 'Idea'),
('idea-post-35', '¿Qué lesiona más: elevaciones bien o mal hechas?', 'Cuál es más lesivo? Elevaciones bien hechas o mal (para la técnica?)', 'Idea'),
('idea-post-36', '¿Por qué no hacerlo online?', 'Pregúntate, porque no de manera online?', 'Idea'),
('idea-post-37', 'Por qué te duele el hombro en press de banca', 'Video haciendo press de banca, y por que te duele haciendo press de banca el hombro, lee la descripción', 'Idea'),
('idea-post-38', 'El hombro no es de plástico: eres una persona', 'Sacando el hombro de plastico, y se dice que el problema es cuando tratan tu hombro como el trozo plástico que tengo, y no es asi, eres una persona, con sentimientos y emociones, con objetivos propios, por lo que no se trata de tratar eso solo', 'Idea'),
('idea-post-39', 'Mi caso: también me dijeron que no volvería a entrenar', 'Mi caso propio, a mi también me dijeron que no volvería a entrenar', 'Idea'),
('idea-post-40', 'Por qué mucha gente no se recupera (hay que currárselo)', 'El problema de que mucha gente no se recupera es porque realmente la recuperación que yo ofrezco es hay que currárselo hay que entrenar y tal pero bueno si eres una persona que entrena y estoy proponiendo empezar a entrenar desde ya creo que es buena opción no?', 'Idea'),
('idea-post-41', 'La diferencia no está en la resonancia, está en lo funcional', 'La diferencia no está en Entrenamiento en lo que debían en la resonancia o la pruebas la diferencia está en cómo eres funcionalmente lo he visto a menudo que persona me resonancia completamente totalmente diferente', 'Idea'),
('idea-post-42', 'Qué es una recuperación de verdad', 'Una recuperación de verdad no es que deje de dolerte al quitar ejercicios o al darte masajes, una completa recuperación es que no te duela al hacer los ejercicios que te dolían con las cargas altas', 'Idea'),
('idea-post-43', 'La readaptación te acerca a tu deporte, no te aleja', 'No te quiero alejar de tu deporte, todo lo contrario con un proceso de readaptación y sabiendo cómo gestionar bien las cargas, te voy a acercar incluso más a tu deporte en menos lo que te espera', 'Idea'),
('idea-post-44', 'Si tu entrenador no revierte la lesión en semanas, huye', 'Si tu entrenador no ha sido que aparece de revertir la situación de tu lesión en 234 semanas máximo huye ahí porque no está haciendo bien', 'Idea'),
('idea-post-45', 'Variantes de elevaciones laterales (abducción)', 'Diferentes elevaciones laterales (abducción)', 'Idea')
on conflict (id) do nothing;
